// lib/screens/groups/group_details_screen.dart

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import '../../services/firestore_service.dart';
import '../../models/app_models.dart';
import '../expenses/add_expense_screen.dart';

class GroupDetailsScreen extends StatefulWidget {
  final ExpenseGroup group;

  const GroupDetailsScreen({Key? key, required this.group}) : super(key: key);

  @override
  State<GroupDetailsScreen> createState() => _GroupDetailsScreenState();
}

class _GroupDetailsScreenState extends State<GroupDetailsScreen> {
  final FirestoreService _firestoreService = FirestoreService();
  List<AppUser> _members = [];

  @override
  void initState() {
    super.initState();
    _loadMembers();
  }

  Future<void> _loadMembers() async {
    final members = <AppUser>[];
    for (final memberId in widget.group.memberIds) {
      final user = await _firestoreService.getUser(memberId);
      if (user != null) members.add(user);
    }
    setState(() => _members = members);
  }

  Future<void> _showSettlement() async {
    final settlements = await _firestoreService.calculateSettlements(widget.group.id);

    if (!mounted) return;

    showModalBottomSheet(
      context: context,
      isScrollControlled: true,
      backgroundColor: Colors.transparent,
      builder: (context) => SettlementSheet(
        group: widget.group,
        settlements: settlements,
        members: _members,
      ),
    );
  }

  void _exportToWhatsApp() {
    final total = widget.group.getTotalExpenses();
    String message = '🔥 *${widget.group.name.toUpperCase()}* 🔥\n\n';
    message += '💰 Total Spent: ₹${total.toStringAsFixed(2)}\n\n';
    message += '*Balances:*\n';

    widget.group.balances.forEach((userId, balance) {
      final member = _members.firstWhere((m) => m.uid == userId);
      final status = balance > 0
          ? 'gets ₹${balance.toStringAsFixed(2)} 💚'
          : balance < 0
          ? 'owes ₹${balance.abs().toStringAsFixed(2)} 💔'
          : 'settled ✅';
      message += '${member.avatar} ${member.name}: $status\n';
    });

    message += '\n_Generated by MUKHLA - Kharche Pai Charcha 🚀_';

    Clipboard.setData(ClipboardData(text: message));
    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(
        content: Text('Copied to clipboard! 📋'),
        backgroundColor: Colors.green,
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        decoration: const BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment.topCenter,
            end: Alignment.bottomCenter,
            colors: [Color(0xFFF3E8FF), Color(0xFFFCE7F3), Colors.white],
          ),
        ),
        child: SafeArea(
          child: Column(
            children: [
              // Header
              Padding(
                padding: const EdgeInsets.all(20),
                child: Row(
                  children: [
                    IconButton(
                      icon: const Icon(Icons.arrow_back),
                      onPressed: () => Navigator.pop(context),
                    ),
                    Expanded(
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Row(
                            children: [
                              Text(
                                widget.group.icon,
                                style: const TextStyle(fontSize: 24),
                              ),
                              const SizedBox(width: 12),
                              Expanded(
                                child: Text(
                                  widget.group.name,
                                  style: const TextStyle(
                                    fontSize: 20,
                                    fontWeight: FontWeight.bold,
                                  ),
                                ),
                              ),
                            ],
                          ),
                          Text(
                            '${widget.group.memberIds.length} members',
                            style: TextStyle(
                              fontSize: 14,
                              color: Colors.grey[600],
                            ),
                          ),
                        ],
                      ),
                    ),
                    IconButton(
                      icon: const Icon(Icons.share),
                      onPressed: _exportToWhatsApp,
                    ),
                  ],
                ),
              ),

              // Stats Row
              Padding(
                padding: const EdgeInsets.symmetric(horizontal: 20),
                child: Row(
                  children: [
                    Expanded(
                      child: _buildStatCard(
                        'Total Spent',
                        '₹${widget.group.getTotalExpenses().toStringAsFixed(2)}',
                        Colors.green,
                      ),
                    ),
                    const SizedBox(width: 12),
                    Expanded(
                      child: _buildStatCard(
                        'Settled',
                        widget.group.balances.values
                            .where((b) => b.abs() < 0.01)
                            .length
                            .toString() +
                            '/${widget.group.balances.length}',
                        Colors.blue,
                      ),
                    ),
                  ],
                ),
              ),

              const SizedBox(height: 20),

              // Quick Actions
              Padding(
                padding: const EdgeInsets.symmetric(horizontal: 20),
                child: Row(
                  children: [
                    Expanded(
                      child: ElevatedButton.icon(
                        onPressed: () async {
                          final result = await Navigator.push(
                            context,
                            MaterialPageRoute(
                              builder: (context) => AddExpenseScreen(
                                group: widget.group,
                                members: _members,
                              ),
                            ),
                          );
                          if (result == true) {
                            // Refresh
                            setState(() {});
                          }
                        },
                        icon: const Icon(Icons.add),
                        label: const Text('Add Expense'),
                        style: ElevatedButton.styleFrom(
                          backgroundColor: const Color(0xFF7C3AED),
                          padding: const EdgeInsets.symmetric(vertical: 14),
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(12),
                          ),
                        ),
                      ),
                    ),
                    const SizedBox(width: 12),
                    Expanded(
                      child: ElevatedButton.icon(
                        onPressed: _showSettlement,
                        icon: const Icon(Icons.account_balance_wallet),
                        label: const Text('Settle Up'),
                        style: ElevatedButton.styleFrom(
                          backgroundColor: const Color(0xFF10B981),
                          padding: const EdgeInsets.symmetric(vertical: 14),
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(12),
                          ),
                        ),
                      ),
                    ),
                  ],
                ),
              ),

              const SizedBox(height: 20),

              // Expenses List
              Expanded(
                child: StreamBuilder<List<Expense>>(
                  stream: _firestoreService.getExpenses(widget.group.id),
                  builder: (context, snapshot) {
                    if (snapshot.connectionState == ConnectionState.waiting) {
                      return const Center(child: CircularProgressIndicator());
                    }

                    if (!snapshot.hasData || snapshot.data!.isEmpty) {
                      return Center(
                        child: Column(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: [
                            const Text('📊', style: TextStyle(fontSize: 60)),
                            const SizedBox(height: 16),
                            Text(
                              'No expenses yet!',
                              style: TextStyle(
                                fontSize: 18,
                                fontWeight: FontWeight.bold,
                                color: Colors.grey[700],
                              ),
                            ),
                            Text(
                              'Add your first expense',
                              style: TextStyle(color: Colors.grey[600]),
                            ),
                          ],
                        ),
                      );
                    }

                    final expenses = snapshot.data!;
                    return ListView.builder(
                      padding: const EdgeInsets.all(20),
                      itemCount: expenses.length,
                      itemBuilder: (context, index) {
                        final expense = expenses[index];
                        final payer = _members.firstWhere(
                              (m) => m.uid == expense.paidBy,
                          orElse: () => AppUser(
                            uid: '',
                            email: '',
                            name: 'Unknown',
                            avatar: '👤',
                          ),
                        );

                        return _buildExpenseCard(expense, payer);
                      },
                    );
                  },
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildStatCard(String label, String value, Color color) {
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(16),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withOpacity(0.05),
            blurRadius: 8,
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            label,
            style: TextStyle(
              fontSize: 12,
              color: Colors.grey[600],
            ),
          ),
          const SizedBox(height: 4),
          Text(
            value,
            style: TextStyle(
              fontSize: 20,
              fontWeight: FontWeight.bold,
              color: color,
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildExpenseCard(Expense expense, AppUser payer) {
    return Container(
      margin: const EdgeInsets.only(bottom: 12),
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(16),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withOpacity(0.05),
            blurRadius: 8,
          ),
        ],
      ),
      child: Row(
        children: [
          Text(payer.avatar, style: const TextStyle(fontSize: 32)),
          const SizedBox(width: 16),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  expense.description,
                  style: const TextStyle(
                    fontSize: 16,
                    fontWeight: FontWeight.bold,
                  ),
                ),
                const SizedBox(height: 4),
                Text(
                  'Paid by ${payer.name} • ${expense.category}',
                  style: TextStyle(
                    fontSize: 14,
                    color: Colors.grey[600],
                  ),
                ),
                Text(
                  'Split between ${expense.splitBetween.length} people',
                  style: TextStyle(
                    fontSize: 12,
                    color: Colors.grey[500],
                  ),
                ),
              ],
            ),
          ),
          Column(
            crossAxisAlignment: CrossAxisAlignment.end,
            children: [
              Text(
                '₹${expense.amount.toStringAsFixed(2)}',
                style: const TextStyle(
                  fontSize: 18,
                  fontWeight: FontWeight.bold,
                  color: Color(0xFF7C3AED),
                ),
              ),
              IconButton(
                icon: const Icon(Icons.delete_outline, size: 20, color: Colors.red),
                onPressed: () async {
                  final confirm = await showDialog<bool>(
                    context: context,
                    builder: (context) => AlertDialog(
                      title: const Text('Delete Expense?'),
                      content: const Text('This cannot be undone.'),
                      actions: [
                        TextButton(
                          onPressed: () => Navigator.pop(context, false),
                          child: const Text('Cancel'),
                        ),
                        TextButton(
                          onPressed: () => Navigator.pop(context, true),
                          child: const Text('Delete', style: TextStyle(color: Colors.red)),
                        ),
                      ],
                    ),
                  );

                  if (confirm == true) {
                    await _firestoreService.deleteExpense(expense.id, widget.group.id);
                  }
                },
              ),
            ],
          ),
        ],
      ),
    );
  }
}

// ============================================================================
// SETTLEMENT SHEET
// ============================================================================

class SettlementSheet extends StatelessWidget {
  final ExpenseGroup group;
  final List<Settlement> settlements;
  final List<AppUser> members;

  const SettlementSheet({
    Key? key,
    required this.group,
    required this.settlements,
    required this.members,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.all(24),
      decoration: const BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.vertical(top: Radius.circular(24)),
      ),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          // Handle
          Container(
            width: 40,
            height: 4,
            decoration: BoxDecoration(
              color: Colors.grey[300],
              borderRadius: BorderRadius.circular(2),
            ),
          ),
          const SizedBox(height: 24),

          // Title
          const Text(
            'Smart Settlement 🎯',
            style: TextStyle(
              fontSize: 24,
              fontWeight: FontWeight.bold,
            ),
          ),
          const SizedBox(height: 8),

          if (settlements.isEmpty)
            const Padding(
              padding: EdgeInsets.all(32),
              child: Column(
                children: [
                  Text('✅', style: TextStyle(fontSize: 60)),
                  SizedBox(height: 16),
                  Text(
                    'Sab settle hai!',
                    style: TextStyle(
                      fontSize: 20,
                      fontWeight: FontWeight.bold,
                      color: Colors.green,
                    ),
                  ),
                  SizedBox(height: 8),
                  Text('No pending payments'),
                ],
              ),
            )
          else ...[
            Container(
              padding: const EdgeInsets.all(16),
              decoration: BoxDecoration(
                color: const Color(0xFFF3E8FF),
                borderRadius: BorderRadius.circular(12),
              ),
              child: Row(
                children: [
                  const Text(
                    '💡',
                    style: TextStyle(fontSize: 24),
                  ),
                  const SizedBox(width: 12),
                  Expanded(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        const Text(
                          'Minimum transactions:',
                          style: TextStyle(fontSize: 12),
                        ),
                        Text(
                          '${settlements.length} payment${settlements.length > 1 ? 's' : ''}',
                          style: const TextStyle(
                            fontSize: 20,
                            fontWeight: FontWeight.bold,
                            color: Color(0xFF7C3AED),
                          ),
                        ),
                      ],
                    ),
                  ),
                ],
              ),
            ),
            const SizedBox(height: 20),

            // Settlements List
            ...settlements.map((settlement) {
              final fromUser = members.firstWhere((m) => m.uid == settlement.fromUserId);
              final toUser = members.firstWhere((m) => m.uid == settlement.toUserId);

              return Container(
                margin: const EdgeInsets.only(bottom: 12),
                padding: const EdgeInsets.all(16),
                decoration: BoxDecoration(
                  gradient: const LinearGradient(
                    colors: [Color(0xFFFFEDD5), Color(0xFFFED7AA)],
                  ),
                  borderRadius: BorderRadius.circular(16),
                ),
                child: Row(
                  children: [
                    Column(
                      children: [
                        Text(fromUser.avatar, style: const TextStyle(fontSize: 32)),
                        Text(
                          fromUser.name,
                          style: const TextStyle(
                            fontSize: 12,
                            fontWeight: FontWeight.bold,
                          ),
                        ),
                      ],
                    ),
                    const SizedBox(width: 16),
                    Expanded(
                      child: Column(
                        children: [
                          const Icon(
                            Icons.arrow_forward,
                            color: Color(0xFF7C3AED),
                            size: 24,
                          ),
                          const SizedBox(height: 4),
                          Text(
                            '₹${settlement.amount.toStringAsFixed(2)}',
                            style: const TextStyle(
                              fontSize: 18,
                              fontWeight: FontWeight.bold,
                              color: Color(0xFF7C3AED),
                            ),
                          ),
                        ],
                      ),
                    ),
                    const SizedBox(width: 16),
                    Column(
                      children: [
                        Text(toUser.avatar, style: const TextStyle(fontSize: 32)),
                        Text(
                          toUser.name,
                          style: const TextStyle(
                            fontSize: 12,
                            fontWeight: FontWeight.bold,
                          ),
                        ),
                      ],
                    ),
                  ],
                ),
              );
            }).toList(),

            const SizedBox(height: 20),

            // Copy Button
            SizedBox(
              width: double.infinity,
              child: ElevatedButton.icon(
                onPressed: () {
                  _copySettlement(context);
                },
                icon: const Icon(Icons.copy),
                label: const Text('Copy for WhatsApp'),
                style: ElevatedButton.styleFrom(
                  backgroundColor: const Color(0xFF10B981),
                  padding: const EdgeInsets.symmetric(vertical: 16),
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(12),
                  ),
                ),
              ),
            ),
          ],

          const SizedBox(height: 20),
        ],
      ),
    );
  }

  void _copySettlement(BuildContext context) {
    String message = '🎯 *SETTLEMENT PLAN* 🎯\n\n';
    message += '*${group.name}*\n\n';

    if (settlements.isEmpty) {
      message += '✅ Sab settle hai!\n\n';
    } else {
      message += 'Minimum ${settlements.length} transaction${settlements.length > 1 ? 's' : ''}:\n\n';
      for (int i = 0; i < settlements.length; i++) {
        final s = settlements[i];
        final fromUser = members.firstWhere((m) => m.uid == s.fromUserId);
        final toUser = members.firstWhere((m) => m.uid == s.toUserId);
        message += '${i + 1}. ${fromUser.avatar} ${fromUser.name} → ${toUser.avatar} ${toUser.name}\n';
        message += '   ₹${s.amount.toStringAsFixed(2)}\n\n';
      }
    }

    message += '_Generated by MUKHLA 🚀_';

    Clipboard.setData(ClipboardData(text: message));
    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(
        content: Text('Copied to clipboard! 📋'),
        backgroundColor: Colors.green,
      ),
    );
  }
}